/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + yy_more_offset >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[yy_more_offset], yytext_ptr, yyleng + 1 ); \
	yyleng += yy_more_offset; \
	yy_prev_more_offset = yy_more_offset; \
	yy_more_offset = 0; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
static yyconst short int yy_acclist[402] =
    {   0,
        2,    2,   96,   94,   95,   92,   94,   95,   92,   95,
       94,   95,   93,   94,   95,   91,   94,   95,    6,   94,
       95,    7,   94,   95,    8,   94,   95,    9,   94,   95,
       10,   94,   95,   11,   94,   95,   12,   94,   95,   13,
       94,   95,   15,   94,   95,   17,   94,   95,   90,   91,
       94,   95,   18,   94,   95,   19,   94,   95,   20,   94,
       95,   23,   94,   95,   25,   94,   95,   27,   94,   95,
       28,   94,   95,   29,   94,   95,   30,   94,   95,   91,
       94,   95,   91,   94,   95,   91,   94,   95,   91,   94,
       95,   91,   94,   95,   91,   94,   95,   91,   94,   95,

       91,   94,   95,   91,   94,   95,   91,   94,   95,   91,
       94,   95,   91,   94,   95,   91,   94,   95,   91,   94,
       95,   91,   94,   95,   91,   94,   95,   91,   94,   95,
       31,   94,   95,   32,   94,   95,   33,   94,   95,   34,
       94,   95,    2,   95,    4,   95,    3,   95,   92,   89,
       93,   91,   14,    1,   90,   91,   21,   24,   26,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   44,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   35,    2,
        3,    3,    5,   16,   22,   91,   91,   91,   91,   91,

       48,   91,   50,   91,   52,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   69,   91,
       68,   91,   91,   91,   91,   91,   91,   46,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   47,
       91,   49,   91,   51,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   56,
       91,   57,   91,   58,   91,   91,   91,   61,   91,   91,
       91,   64,   91,   91,   84,   91,   65,   91,   42,   91,
       81,   91,   91,   91,   53,   91,   54,   91,   55,   91,
       91,   91,   91,   66,   91,   67,   91,   91,   91,   60,

       91,   91,   38,   91,   91,   91,   43,   91,   59,   91,
       91,   91,   91,   41,   91,   91,   62,   91,   45,   91,
       91,   91,   91,   91,   40,   91,   91,   91,   91,   70,
       91,   80,   91,   63,   91,   91,   91,   91,   75,   91,
       74,   91,   91,   91,   91,   76,   91,   91,   91,   91,
       91,   91,   88,   91,   91,   91,   78,   91,   91,   73,
       91,   79,   91,   36,   91,   91,   91,   91,   83,   91,
       91,   91,   91,   37,   87,   91,   82,   91,   91,   39,
       91,   91,   91,   91,   86,   91,   85,   91,   91,   91,
       91,   91,   91,   91,   71,   91,   72,   91,   91,   77,

       91
    } ;

static yyconst short int yy_accept[267] =
    {   0,
        1,    1,    1,    2,    3,    4,    6,    9,   11,   13,
       16,   19,   22,   25,   28,   31,   34,   37,   40,   43,
       46,   49,   53,   56,   59,   62,   65,   68,   71,   74,
       77,   80,   83,   86,   89,   92,   95,   98,  101,  104,
      107,  110,  113,  116,  119,  122,  125,  128,  131,  134,
      137,  140,  143,  145,  147,  149,  150,  150,  151,  152,
      153,  154,  154,  155,  157,  158,  159,  160,  161,  162,
      163,  164,  165,  166,  167,  168,  169,  171,  172,  173,
      174,  175,  176,  177,  178,  179,  180,  181,  182,  183,
      184,  185,  186,  187,  188,  189,  190,  191,  192,  193,

      194,  195,  196,  197,  198,  199,  200,  201,  203,  205,
      207,  208,  209,  210,  211,  212,  213,  214,  215,  216,
      217,  218,  219,  221,  223,  224,  225,  226,  227,  228,
      230,  231,  232,  233,  234,  235,  236,  237,  238,  239,
      240,  242,  244,  246,  247,  248,  249,  250,  251,  252,
      253,  254,  255,  256,  257,  258,  259,  260,  262,  264,
      266,  266,  267,  268,  270,  271,  272,  274,  275,  277,
      279,  281,  283,  284,  285,  287,  289,  291,  292,  293,
      294,  296,  298,  299,  300,  302,  303,  305,  306,  307,
      309,  311,  312,  313,  314,  316,  317,  317,  317,  319,

      321,  322,  323,  324,  325,  327,  328,  329,  330,  332,
      334,  336,  337,  338,  339,  341,  343,  344,  345,  346,
      346,  346,  348,  349,  350,  351,  352,  353,  355,  356,
      357,  359,  360,  362,  364,  365,  365,  366,  367,  368,
      369,  371,  372,  373,  374,  375,  377,  379,  380,  382,
      383,  384,  385,  387,  389,  390,  391,  392,  393,  394,
      395,  397,  399,  400,  402,  402
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    8,    9,    7,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,    7,    7,   41,   42,   43,
       44,   45,    7,   46,   47,   48,   49,   50,   51,   52,
       53,    7,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    1,    1,    1,
        1,    5,    1,    1,    1,    1,    1,    4,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[272] =
    {   0,
        0,    0,   55,   57,  307,  308,   60,   68,  301,    0,
        0,  308,  308,  308,  308,  308,  308,  308,  279,  288,
      291,   55,  308,  308,  277,  275,  275,  308,  308,  308,
      308,   36,  255,  262,   26,  265,  247,   23,   48,   59,
      251,  248,   45,   38,   39,  250,   54,   49,  308,  308,
      308,  267,    0,  308,   81,   98,  286,  308,    0,    0,
      308,  274,  308,   85,  263,  308,  308,  247,  240,  243,
      248,  239,   89,  242,  242,  236,   63,  233,  231,  237,
       61,  234,  228,  239,  227,  229,  230,   81,   74,  226,
      230,  223,  222,  231,   97,  308,    0,  107,  109,  308,

      308,  308,  109,  230,  218,  232,  215,    0,    0,    0,
      228,  217,  213,  224,  214,  210,  215,  219,  206,  112,
      238,  206,    0,    0,  211,   83,  202,  201,  212,    0,
      213,  210,  209,  208,   89,  117,  203,  196,  194,  193,
        0,    0,    0,  195,  192,  189,  187,  182,  185,  187,
      196,  195,  184,  181,  179,  181,  181,    0,    0,    0,
       93,  181,  181,    0,  183,  176,    0,  173,    0,  189,
        0,    0,  176,  182,    0,    0,    0,  185,  179,  179,
        0,    0,  167,  165,  181,  170,    0,  162,  161,    0,
        0,  160,  175,  171,    0,  161,  156,  157,    0,    0,

      150,  161,  147,  153,    0,  152,  154,  143,    0,    0,
        0,  147,  146,  157,    0,    0,  144,  155,  143,  143,
      152,    0,  153,  141,  141,  137,  135,    0,  136,  128,
        0,  142,    0,    0,  308,  139,  126,  133,  120,  120,
        0,  119,  114,  121,  308,    0,    0,  103,    0,  114,
      113,  101,    0,    0,  101,  101,  109,  112,  123,  104,
        0,    0,   86,    0,  308,  157,  162,  167,  108,  172,
      176
    } ;

static yyconst short int yy_def[272] =
    {   0,
      265,    1,  266,  266,  265,  265,  265,  265,  267,  268,
      269,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  269,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  265,  265,
      265,  265,  270,  265,  271,  265,  267,  265,  268,  269,
      265,  265,  265,  269,  265,  265,  265,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  265,  270,  271,  271,  265,

      265,  265,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      265,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  265,  265,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  265,
      265,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  265,  265,  269,  269,  269,  269,
      269,  269,  269,  269,  265,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,    0,  265,  265,  265,  265,  265,
      265
    } ;

static yyconst short int yy_nxt[366] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       11,   32,   11,   33,   34,   35,   36,   37,   11,   38,
       39,   40,   41,   11,   42,   43,   44,   45,   46,   47,
       48,   11,   11,   49,   50,   51,   52,   54,   54,   54,
       54,   56,   56,   56,   76,   77,   55,   72,   55,   56,
       56,   56,   64,   64,   64,   64,   68,   73,   80,   78,
       85,   87,   69,   79,   89,   92,   88,   94,   86,   93,
       81,   90,   99,  116,  122,   95,  117,  100,   82,   56,

       56,   56,   64,   64,   64,   64,  108,  109,  110,  132,
      118,   60,  123,  130,  131,  139,  140,  164,  265,  165,
       99,  264,  133,  265,  111,  100,  141,  142,  143,  158,
      159,  160,  173,  112,  175,  176,  177,  263,  174,  197,
      198,  261,  262,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  144,  250,  249,  178,   53,   53,   53,
       53,   53,   57,  248,   57,   57,   57,   59,  247,   59,
       59,   59,   97,  246,  245,   97,   98,  244,  243,   98,
       98,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,

      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  172,  171,  170,  169,  168,  167,  166,
      163,  162,  161,  157,  156,  155,  154,  153,  152,  151,
      150,  149,  148,  147,  146,  145,  138,  137,  136,  135,
      134,  129,  128,  127,  126,  125,  124,  121,  120,  119,
      115,  114,  113,  107,  106,  105,  104,  103,  102,  101,
       58,   96,   91,   84,   83,   75,   74,   71,   70,   67,

       66,   65,   63,   62,   61,   58,  265,    5,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265
    } ;

static yyconst short int yy_chk[366] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    4,
        4,    7,    7,    7,   38,   38,    3,   35,    4,    8,
        8,    8,   22,   22,   22,   22,   32,   35,   40,   39,
       43,   44,   32,   39,   45,   47,   44,   48,   43,   47,
       40,   45,   55,   77,   81,   48,   77,   55,   40,   56,

       56,   56,   64,   64,   64,   64,   73,   73,   73,   89,
       77,  269,   81,   88,   88,   95,   95,  126,   98,  126,
       99,  263,   89,   98,   73,   99,  103,  103,  103,  120,
      120,  120,  135,   73,  136,  136,  136,  260,  135,  161,
      161,  259,  259,  258,  257,  256,  255,  252,  251,  250,
      248,  244,  243,  103,  242,  240,  136,  266,  266,  266,
      266,  266,  267,  239,  267,  267,  267,  268,  238,  268,
      268,  268,  270,  237,  236,  270,  271,  232,  230,  271,
      271,  229,  227,  226,  225,  224,  223,  221,  220,  219,
      218,  217,  214,  213,  212,  208,  207,  206,  204,  203,

      202,  201,  198,  197,  196,  194,  193,  192,  189,  188,
      186,  185,  184,  183,  180,  179,  178,  174,  173,  170,
      168,  166,  165,  163,  162,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  140,
      139,  138,  137,  134,  133,  132,  131,  129,  128,  127,
      125,  122,  121,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  107,  106,  105,  104,   94,   93,   92,   91,
       90,   87,   86,   85,   84,   83,   82,   80,   79,   78,
       76,   75,   74,   72,   71,   70,   69,   68,   65,   62,
       57,   52,   46,   42,   41,   37,   36,   34,   33,   27,

       26,   25,   21,   20,   19,    9,    5,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() (yy_more_offset = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	yy_more_offset = yy_prev_more_offset; \
	yyleng -= yy_more_offset; \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "scanner.lpp"
#define INITIAL 0
/*
 * MONA
 * Copyright (C) 1997-2008 BRICS.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the  Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
 * USA.
 */
#define YY_NO_UNPUT 1
#define YY_NEVER_INTERACTIVE 1
#line 28 "scanner.lpp"
#include <stdio.h>
#include <string.h>
#include "untyped.h"
#include "parser.h"
#include "deque.h"
#include "lib.h"
#include "printline.h"      
#include "env.h"
#include "../BDD/bdd.h"

using std::cout;

extern SymbolTable symbolTable;
extern AutLib lib;
extern Options options;
extern YYLTYPE yylloc;    

void copyString(char*);
int get_next_char(char*);  
void loadFile(char *s);
void yyerror(const char *s);

#define MYBUFFER_SIZE 1024  

class FileInfo {
public:
  unsigned lineno; /* linenumber */
  unsigned pos; /* position in line number lineno */
  int prevnl; /* previous char was '\n' */
  char *filename; /* name of the file */
  unsigned number; /* number of the file in the include-chain */
  unsigned next; /* pointer into inputbuffer - where to read next char */
  unsigned bufferused; /* number of chars read into inputbuffer */
  char inputbuffer[MYBUFFER_SIZE]; /* buffer containing inputfile blocks */
  FILE *handle; /* file handle */
};

Deque<FileInfo> loadStack; /* stack of file info */

Deque<Deque<char *> *> dependencies; /* list of dependencies */
Deque<FileSource *> source; /* list of source-file text */ 
Deque<char *> fileNames; /* list of file names */
Deque<char> currentLine; /* contains the current line being parsed */

Deque<char *> currentDir;
char *file = "";
unsigned pos = 0;
int prevnl = 0;
int filenumber = 0;

char mybuffer[MYBUFFER_SIZE]; /* input buffer used in YY_INPUT */
int next = 0;
int bufferused = 0;

#define SETPOS(p) \
 yylloc.first_line = yylineno; yylloc.first_column = pos-yyleng-p+1

#define YY_INPUT(buf,result,max_size) result = get_next_char(buf)
/* Definitions */
/* Rules */
#define CCOMMENT 1

#line 700 "scanner.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 99 "scanner.lpp"


#line 854 "scanner.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 266 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 308 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 101 "scanner.lpp"
BEGIN(CCOMMENT);
	YY_BREAK

case 2:
YY_RULE_SETUP
#line 103 "scanner.lpp"
/* ignore */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 104 "scanner.lpp"
/* ignore */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 105 "scanner.lpp"
/* ignore */
	YY_BREAK
case YY_STATE_EOF(CCOMMENT):
#line 106 "scanner.lpp"
yyerror("end-of-file in comment\n");
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 107 "scanner.lpp"
BEGIN(INITIAL);
	YY_BREAK

case 6:
YY_RULE_SETUP
#line 110 "scanner.lpp"
SETPOS(0); return tokMODULO;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 111 "scanner.lpp"
SETPOS(0); return tokAND;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 112 "scanner.lpp"
SETPOS(0); return tokLPAREN;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 113 "scanner.lpp"
SETPOS(0); return tokRPAREN;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 114 "scanner.lpp"
SETPOS(0); return tokSTAR;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 115 "scanner.lpp"
SETPOS(0); return tokPLUS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 116 "scanner.lpp"
SETPOS(0); return tokCOMMA;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 117 "scanner.lpp"
SETPOS(1); return tokMINUS;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 118 "scanner.lpp"
SETPOS(0); return tokARROW;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 119 "scanner.lpp"
SETPOS(1); return tokDOT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 120 "scanner.lpp"
SETPOS(0); return tokINTERVAL;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 121 "scanner.lpp"
SETPOS(1); return tokSLASH;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 122 "scanner.lpp"
SETPOS(0); return tokCOLON;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 123 "scanner.lpp"
SETPOS(0); return tokSEMICOLON;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 124 "scanner.lpp"
SETPOS(1); return tokLESS;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 125 "scanner.lpp"
SETPOS(1); return tokLESSEQ;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 126 "scanner.lpp"
SETPOS(0); return tokBIIMPL;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 127 "scanner.lpp"
SETPOS(1); return tokEQUAL;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 128 "scanner.lpp"
SETPOS(0); return tokIMPL;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 129 "scanner.lpp"
SETPOS(1); return tokGREATER;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 130 "scanner.lpp"
SETPOS(0); return tokGREATEREQ;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 131 "scanner.lpp"
SETPOS(0); return tokLBRACKET;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 132 "scanner.lpp"
SETPOS(0); return tokSETMINUS;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 133 "scanner.lpp"
SETPOS(0); return tokRBRACKET;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 134 "scanner.lpp"
SETPOS(0); return tokUP;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 135 "scanner.lpp"
SETPOS(0); return tokLBRACE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 136 "scanner.lpp"
SETPOS(0); return tokOR;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 137 "scanner.lpp"
SETPOS(0); return tokRBRACE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "scanner.lpp"
SETPOS(1); return tokNOT;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 139 "scanner.lpp"
SETPOS(0); return tokNOTEQUAL;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 140 "scanner.lpp"
SETPOS(0); return tokM2LSTR;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 141 "scanner.lpp"
SETPOS(0); return tokM2LTREE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 142 "scanner.lpp"
SETPOS(1); return tokEMPTY;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 143 "scanner.lpp"
SETPOS(1); return tokUNIVERSE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 144 "scanner.lpp"
SETPOS(1); return tokUNION;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 145 "scanner.lpp"
SETPOS(1); return tokINTER;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 146 "scanner.lpp"
SETPOS(1); return tokTRUE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 147 "scanner.lpp"
SETPOS(1); return tokFALSE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 148 "scanner.lpp"
SETPOS(1); return tokIN;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 149 "scanner.lpp"
SETPOS(1); return tokNOTIN;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 150 "scanner.lpp"
SETPOS(1); return tokSUB;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 151 "scanner.lpp"
SETPOS(1); return tokALL0;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 152 "scanner.lpp"
SETPOS(1); return tokEX0;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 153 "scanner.lpp"
SETPOS(1); return tokALL1;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 154 "scanner.lpp"
SETPOS(1); return tokEX1;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 155 "scanner.lpp"
SETPOS(1); return tokALL2;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 156 "scanner.lpp"
SETPOS(1); return tokEX2;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 157 "scanner.lpp"
SETPOS(1); return tokVAR0;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 158 "scanner.lpp"
SETPOS(1); return tokVAR1;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 159 "scanner.lpp"
SETPOS(1); return tokVAR2;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 160 "scanner.lpp"
SETPOS(1); return tokLET0;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 161 "scanner.lpp"
SETPOS(1); return tokLET1;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 162 "scanner.lpp"
SETPOS(1); return tokLET2;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 163 "scanner.lpp"
SETPOS(1); return tokGUIDE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 164 "scanner.lpp"
SETPOS(1); return tokCONST;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 165 "scanner.lpp"
SETPOS(1); return tokPRED;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 166 "scanner.lpp"
SETPOS(1); return tokMACRO;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 167 "scanner.lpp"
SETPOS(1); return tokASSERT;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 168 "scanner.lpp"
SETPOS(1); return tokUNIVROOT;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 169 "scanner.lpp"
SETPOS(1); return tokTREE;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 170 "scanner.lpp"
SETPOS(1); return tokWS1S;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 171 "scanner.lpp"
SETPOS(1); return tokWS2S;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 172 "scanner.lpp"
SETPOS(1); return tokMIN;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 173 "scanner.lpp"
SETPOS(1); return tokMAX;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 174 "scanner.lpp"
SETPOS(1); return tokWHERE;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 175 "scanner.lpp"
SETPOS(1); return tokDEFAULT1;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 176 "scanner.lpp"
SETPOS(1); return tokDEFAULT2;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 177 "scanner.lpp"
SETPOS(1); return tokINCLUDE;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 178 "scanner.lpp"
SETPOS(1); return tokIMPORT;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 179 "scanner.lpp"
SETPOS(1); return tokEXPORT;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 180 "scanner.lpp"
SETPOS(1); return tokPREFIX;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 181 "scanner.lpp"
SETPOS(1); return tokINSTATESPACE;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 182 "scanner.lpp"
SETPOS(1); return tokEXECUTE;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 183 "scanner.lpp"
SETPOS(1); return tokLASTPOS;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 184 "scanner.lpp"
SETPOS(1); return tokALLPOS;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 185 "scanner.lpp"
SETPOS(1); return tokTYPE;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 186 "scanner.lpp"
SETPOS(1); return tokSOMETYPE;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 187 "scanner.lpp"
SETPOS(1); return tokVARIANT;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 188 "scanner.lpp"
SETPOS(1); return tokSUCC;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 189 "scanner.lpp"
SETPOS(1); return tokCONSTTREE;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 190 "scanner.lpp"
SETPOS(1); return tokTREEROOT;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 191 "scanner.lpp"
SETPOS(1); return tokRESTRICT;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 192 "scanner.lpp"
SETPOS(1); return tokVERIFY;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 193 "scanner.lpp"
{SETPOS(1); yytext[strlen(yytext)-1] = 0;  
		 copyString(yytext); return tokSTRING;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 195 "scanner.lpp"
SETPOS(1); copyString(yytext); return tokINT;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 196 "scanner.lpp"
SETPOS(1); copyString(yytext); return tokNAME;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 197 "scanner.lpp"
/* ignore */
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 198 "scanner.lpp"
/* ignore */
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 199 "scanner.lpp"
yyerror("illegal character");
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 201 "scanner.lpp"
ECHO;
	YY_BREAK
#line 1427 "scanner.cpp"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 266 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 266 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 265);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 201 "scanner.lpp"


/* Subroutines */

void copyString(char *s)
{
  char *str = new char[strlen(s)+1];
  strcpy(str, s);
  str = symbolTable.insertString(str);
  yylval.string = str;
}

void yyerror(const char *s)
{ 
  cout << "Error in file '" << file
       << "' near line " << yylineno << ": " << s << "\n"
       << "Execution aborted\n";
  exit(-1);
}

int yywrap() {
  unsigned i;

  /* pop current directory */
  delete[] currentDir.pop_back();

  /* dependency info */
  if (options.separateCompilation) {
    Deque<char *> *d = dependencies.pop_back();
    lib.openDir(file, d);
    delete d; 
  }

  /* close file */
  fclose(yyin);

  /* done? */
  if (loadStack.size() == 0)
    return -1;

  /* return to previous file */
  FileInfo f = loadStack.pop_back();
  yylineno = f.lineno;
  pos = f.pos;
  prevnl = f.prevnl;
  file = f.filename;
  filenumber = f.number;
  next = f.next;
  bufferused = f.bufferused;
  strncpy(mybuffer, f.inputbuffer, MYBUFFER_SIZE);
  yyin = f.handle;
  
  /* get currentline contents */
  currentLine.reset(); 
  for (i = 0; i < strlen(source.get(filenumber-1)->top()); i++)
    currentLine.push_back((source.get(filenumber-1)->top())[i]);
  delete[] source.get(filenumber-1)->pop_back();

  return 0;
}

void loadFile(char *s) {
  unsigned i,n;
  char *line;
  char *ss;

  /* find current directory */
  if (!currentDir.empty() && s[0] != '/') {
    ss = new char[strlen(currentDir.top())+strlen(s)+1];
    strcpy(ss, currentDir.top()); 
  }
  else {
    ss = new char[strlen(s)+1];
    ss[0] = 0;
  }
  strcat(ss, s);
  unsigned t = strlen(ss);
  while (t > 0 && ss[t-1] != '/')
    t--;
  char *cd = new char[t+1];
  strncpy(cd, ss, t);
  cd[t] = 0;
  currentDir.push_back(cd);

  if (filenumber > 0) {
    /* save status for current file on stack */
    FileInfo f;
    f.lineno = yylineno;
    f.pos = pos;
    f.prevnl = prevnl;
    f.filename = file;
    f.number = filenumber;
    f.next = next;
    f.bufferused = bufferused;
    strncpy(f.inputbuffer, mybuffer, MYBUFFER_SIZE);
    f.handle = yyin;
    loadStack.push_back(f);
    
    /* store current line source */
    line = new char[sizeof(char)*currentLine.size()+1]; 
    line[currentLine.size()] = '\0';
    for (n = 0; n < currentLine.size(); n++) 
      line[n] = currentLine.get(n);
    source.get(filenumber-1)->push_back(line);      
  }

  /* store info on new file in list */
  file = new char[strlen(ss)+1];
  strcpy(file, ss);
  delete[] ss;
  file = symbolTable.insertString(file);
  fileNames.push_back(file);
  source.push_back(new FileSource);

  /* open file */
  for (i = 0; i+1 < loadStack.size(); i++)
    if (strcmp(loadStack.get(i).filename, file) == 0)
      yyerror("cyclic include");
  if (!(yyin = fopen(file, "r"))) {
    cout << "Unable to open file '" << file << "'\n"
	 << "Execution aborted\n";
    exit(-1);
  }
  currentLine.reset(); 
  filenumber++;
  pos = 0;
  prevnl = 0;
  yylineno = 1;
  next = bufferused = 0;

  /* find dependencies */
  if (options.separateCompilation) {
    dependencies.push_back(new Deque<char *>);
    for (Deque<Deque<char *> *>::iterator d = dependencies.begin();
	 d != dependencies.end(); d++)
      (*d)->push_back(file);
  }
}

int get_next_char(char *buf) {
  char *line; 
  unsigned n;
  int c;
  
  if (next == bufferused) {
    /* get a new chunk from the file */
    bufferused = fread(mybuffer, 1, MYBUFFER_SIZE, yyin);
    next = 0;
  }
  if (next == bufferused || mybuffer[next] == '\n') {
    /* move to next line */
    line = new char[currentLine.size()+1]; 
    line[currentLine.size()] = '\0'; 
    for (n = 0; n < currentLine.size(); n++) 
      line[n] = currentLine.get(n); 
    source.get(filenumber-1)->push_back(line);      
    currentLine.reset(); 
  }
  if (next < bufferused) {
    /* end-of-file not reached yet */
    c = mybuffer[next++]; 
    if (prevnl) {
      prevnl = 0;
      pos = 0;
    }
    pos++; 
    if (c == '\n') 
      prevnl = 1; 
    else
      currentLine.push_back(c); 
    buf[0] = c;
    return 1;
  }
  else {
    pos++; 
    return YY_NULL; 
  }
}
